---

# file: roles/lb/tasks/main.yaml

- name: install nginx
  become: true
  yum: name=nginx state=present

- name: configure nginx
  become: true
  template: src=nginx_conf.j2 dest=/etc/nginx/nginx.conf
  with_dict: "{{ apps[app] }}"

- name: start nginx
  become: true
  service:
    name: nginx
    state: started

- name: open firewall port 80
  become: true
  command: "{{item}}"
  with_items:
    - firewall-cmd --permanent --zone=public --add-port=80/tcp
    - firewall-cmd --reload
