---

# file: roles/common/tasks/main.yaml

- name: configure resolv.conf
  become: true
  template: src=resolv_conf.j2 dest=/etc/resolv.conf
  with_dict: "{{ zones[zone] }}"

- name: add epel repo
  become: true
  yum: name={{epel_repo}} state=present

- name: install required base packages
  become: true
  yum: name={{item}} state=installed
  with_items:
    - wget
    - curl
    - vim-enhanced
    - yum-utils
    - deltarpm
    - lsof


## To speed up processing disabled this.
#- name: update all packages
#  become: true
#  yum: update_cache=yes name=* state=latest

