---

# file: roles/common/tasks/main.yaml

- name: configure resolv.conf
  sudo: true
  template: src=resolv_conf.j2 dest=/etc/resolv.conf
  with_dict: zones[zone]

- name: add epel repo
  sudo: true
  yum: name={{epel_repo}} state=present

- name: install required base packages
  sudo: true
  yum: name={{item}} state=installed
  with_items:
    - wget
    - curl
    - vim-enhanced
    - yum-utils
    - deltarpm
    - lsof

## To speed up processing disabled this.
#- name: update all packages
#  sudo: true
#  yum: update_cache=yes name=* state=latest

